### ISSUE TITLE
Starnet weights

### ISSUE THREAD

**Issue by PawelPleskaczynski** [nekitmm/starnet#1]
Hello,
First of all, that's a very cool project, for me it works great, it helps to remove stars easily from astrophotos for easier nebulosity processing. I wish the weights were stored in this GitHub repository (maybe on master branch, maybe on separate branch) for easier updating. If you would update the weights, users would have to download and update them manually, but if they were stored in this repository, updating them locally would be as easy as typing `git pull`! :smile: 

You'd have to use https://git-lfs.github.com/ because there's a 100MB/file limit on regular repos

**Comment by nekitmm** [comment]
Pushed files to lfs, but the "Download ZIP" button here on the website doesn't fetch lfs files though... I think this is a known issue and for many users will be a problem...
