### ISSUE TITLE
Looking to freeze trained data for PI

### ISSUE THREAD

**Issue by patdufour** [nekitmm/starnet#11]
Hi Nikita,

actually working to train with new data using my instrument that generate stars with spikes. Slowly it seems going well. I was wondering how do you proceed to generate both .pb freezed files (L and RGB) model in order to use with PI?

thanks!

**Comment by nekitmm** [comment]
Hi!

I don't remember all the details, but I used a freeze_graph.py script. Some thing like described in this blog post:

https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

**Comment by patdufour** [comment]
Thanks for your response Nikita,
unfortunately the script asks for the output list and I'm not sure what needs to be included to be compatible with the PI module. If I include all the variables, it generates a much larger file than the one for the RGB version and the starnet script returns an 'invalid checkpoint' error.

**Comment by nekitmm** [comment]
I think output should be "generator/g_deconv7/Sub"

**Comment by patdufour** [comment]
Hi Nikita, almost there. The size and generated structure are really close but I receive an error from PI which is not ease to debug. Does this remind you of anything?

![Sans titre](https://user-images.githubusercontent.com/68965254/89221679-aef58b80-d5a1-11ea-8aef-9a69e5d2890e.png)

**Comment by nekitmm** [comment]
Hm, this is weird, I don't remember having any problems - just froze the graph and used it...

Here is the code I used to do this, maybe this will help somehow:

import os
import freeze_graph

checkpoint_state_name = "model.ckpt"
input_graph_name = "starnet.pb"
output_graph_name = "starne_weights.pb"

input_graph_path = os.path.join("./", input_graph_name)
input_saver_def_path = ""
input_binary = False
input_checkpoint_path = os.path.join("./", 'saved_checkpoint')


output_node_names = "generator/g_deconv7/Sub" 
restore_op_name = "save/restore_all" # not used
filename_tensor_name = "save/Const:0" # not used
output_graph_path = os.path.join("./", output_graph_name)
clear_devices = False

freeze_graph.freeze_graph("./starnet_generator.pb",
                          "",
                          True,
                          "./model.ckpt",
                          output_node_names,
                          restore_op_name,
                          filename_tensor_name,
                          "./starnet_generator_weights.pbtxt",
                          clear_devices,
                          "")

**Comment by patdufour** [comment]
Doesn't help, same error! Do you have the script that was used to generate the previous step, aka saving the input_graph_name starnet.pb from a checkpoint state?

**Comment by nekitmm** [comment]
Yes! I uploaded the script - export.py - try using that!

**Comment by patdufour** [comment]
So based on the actual git repository, the gen_sub list at least one item that is not in the graph:

"AssertionError: generator/g_conv1/LeakyRelu/alpha is not in graph"

**Comment by nekitmm** [comment]
Well, it seems to be working on my end - generator/g_conv1/LeakyRelu/alpha is in the model if you look at model.py file

Not sure what is the problem here....

**Comment by patdufour** [comment]
You know what? I can't find any 'generator/g_conv1/LeakyRelu/alpha' in the file on this git.

**Comment by nekitmm** [comment]
Try now with the new list!

**Comment by patdufour** [comment]
Really sorry, just another error message on another parameter: 

generator/g_conv1/batch_normalization/FusedBatchNorm

**Comment by nekitmm** [comment]
Ok, let's take a step back here. I uploaded all the necessary files. I just cloned the repo and everything works as expected.

Please try to clone the repo and run
```
python starnet.py export
python freeze.py
```

Everything should work!

**Comment by patdufour** [comment]
I have re-installed python environment so that I use the same config that was mentioned in the read.me file. Python 3.6.3, tensorflow-gpu (1.4.0). I was previously using TF 1.15 and noticed that some tensor names had changed. I'm still facing not found tensor names in the graph (example : generator/g_conv1/batch_normalization/AssignMovingAvg/sub/x) . How did you generate the gen_sub.txt ? Does it come from the starnet.pbtxt file?

**Comment by patdufour** [comment]
I finally managed to adequately generate the file by extracting all the nodes from the generators with the following line in the export.py file.

gen_layers = [n.name for n in tf.get_default_graph().as_graph_def().node if n.name.find("generator") == 0]

thanks for your help!

**Comment by nekitmm** [comment]
Let me know if you were able to generate a working checkpoint file for PI!

**Comment by patdufour** [comment]
Will certainly do when completed. Why does your model differ from the proposed PAN one? Some relu are not performed in some generator's layers (ex. g_conv8). In the paper they added a relu rectifier at the end.

**Comment by nekitmm** [comment]
Not sure what PAN is? Overall, I tried to combine approaches from different papers and tried to find combination that works better, in contract to just using some particular one that was published. Also, I don't have g_conv8 in the model, lol, and what do you mean "Some relu are not performed in some generator's layers"? All of them have ReLUs!

**Comment by patdufour** [comment]
Ok thanks for your comments. I was refering to table II of this paper https://arxiv.org/pdf/1706.09138.pdf 

regards

**Comment by nekitmm** [comment]
I see. I had a very crappy GPU with little memory, so I used lower resolution of input (256 vs 512) so I dropped one layer of convolutions!
