### ISSUE TITLE
no support tif files from photoshop?

### ISSUE THREAD

**Issue by xmeter** [nekitmm/starnet#19]
hi nekitmm， i saved a milky way core tif in photoshop in 16 bit, but when i go to starnet++, it always say only support 16 bit files, any idea?

**Comment by nekitmm** [comment]
No idea here... I always use PS and never had any issues with that!

**Comment by xmeter** [comment]
I saw the log showing 4 pixel/sample, maybe this is the cause?

**Comment by nekitmm** [comment]
Not sure what you are talking about? 4 pixel/sample?

**Comment by nekitmm** [comment]
Probably your file has 4 channels (alpha channel included) or something fancy like this...

**Comment by xmeter** [comment]
I think so, I will try to delete alpha channel and try again. Thanks.

**Comment by Epoxid2** [comment]
GIMP does the same, always writes an alpha-channel, too. I just created a pull request for a version which can process alpha-channel tiffs by discarding the alpha.
