### ISSUE TITLE
Scipy error

### ISSUE THREAD

**Issue by ajeb78** [nekitmm/starnet#24]
On running starnet I get the following error:

adrian@mononoke:~/starnet$ python starnet.py transform ../Flat/Keeps/M42-and-M43.png
Traceback (most recent call last):
  File "/home/adrian/starnet/starnet.py", line 105, in <module>
    import transform
  File "/home/adrian/starnet/transform.py", line 19, in <module>
    from scipy.misc import toimage
ImportError: cannot import name 'toimage' from 'scipy.misc' (/usr/lib/python3/dist-packages/scipy/misc/__init__.py)

My python installation is python 3.9.7 and scipy 1.6.0.

It appears that the toimage function in scipy was deprecated and then removed, the official recommendaton is to use a function from the pillow library instead (Image.fromarray).

**Comment by nekitmm** [comment]
Thanks for letting me know! You can rewrite those lines for now to use pillow instead as suggested, I will update the repo as soon as I have time!
