### ISSUE TITLE
no interface in v2 version for MacOS

### ISSUE THREAD

**Issue by abhassine** [nekitmm/starnet#28]
Hello,
I didn't find any interface for MacOS to run it outside Pix

Any guidance please to run it on MacOS ??

**Comment by Ripwords** [comment]
Download the MacOS CLI tool here https://starnetastro.com/wp-content/uploads/2022/03/StarNetv2CLI_MacOS.zip

Then if you would like a GUI for it you can download it here https://github.com/Ripwords/starnetGUI/releases/download/starnetGUI-v0.6.1/starnetGUI_0.6.1_x64.dmg
