### ISSUE TITLE
Unsupported API version 162(expected <= 160)

### ISSUE THREAD

**Issue by AbnerLwt** [nekitmm/starnet#3]
Hello Nekitmm:

Thanks your work! But there was an error happened during my installation of  StarNet on my Mac OS X 10.15:
Log:
Installing 1 module(s):
/Applications/PixInsight/bin/StarNet-pxm.dylib
<* failed *>
*** PixInsight API Error: Module: /Applications/PixInsight/bin/StarNet-pxm.dylib: Unsupported API version 162 (expected = 160).: Module load error

What this error means and how could I fix it?

**Comment by nekitmm** [comment]
What is the version of your PI installation? Maybe you should update it to more recent version!

**Comment by nekitmm** [comment]
Lol, I am closing the issue  - the question is about C++ version of the software, you should better ask it on CN!
