### ISSUE TITLE
scipy toimage is deprecated and has been removed

### ISSUE THREAD

**Issue by paolostivanin** [nekitmm/starnet#5]
Hi,
toimage from scipy.misc has been removed since version 1.2.
One alternative could be to use PIL instead :)

**Comment by nekitmm** [comment]
Thanks! This whole thing is outdated by now, I will invest time to update it in the nearest future!

**Comment by Leepee** [comment]
To be clear, you need:

Python 3.6
Tensorflow-GPU 1.4.0
CUDA version 8
CUDA NN version 6
Scipy version 1.1
numpy
matplotlib

Just my findings to this point trying to get it working with a conda environment! :)

**Comment by nekitmm** [comment]
Pushed a new version in TF2! Should be up to date now!
