### ISSUE TITLE
OSX save issue

### ISSUE THREAD

**Issue by lpalbou** [nekitmm/starnet#7]
Hi, just passing by on what seems to be a very cool projet. I saw a picture on instagram of someone using your code to remove stars and the effect was amazing.

While trying to test if myself, I run into a save error:
```
```

Which is linked to that line: https://github.com/nekitmm/starnet/blob/master/transform.py#L122

Probably removing the "./" would be a good idea as i was trying to run your script with an absolute path and not a relative path and it couldn't save due to a weird path :)

PS: also didn't managed to have the plugin installed with pixinsight 1.8, including with recursive search - even though the files were there. Maybe something changed with the versions ? It's not related to your warning on AVX since i could run the script successfully.

Anyhow, great job and interesting project !

**Comment by nekitmm** [comment]
Hi! Thanks for all the kind words!

I can't see it - what is the error you ran into? It shows just a blank grey rectangle...

About PI - what exact version do you have - 1.8.8-5? If yes, then it won't work on Mac, some issue with digital signatures, you can find more info on PI forums. Your options for now are either get back to 1.8.8-4 or wait for 1.8.8-6 which should resolve the issue (probably).
