### ISSUE TITLE
Training the AI 

### ISSUE THREAD

**Issue by Leepee** [nekitmm/starnet#9]
Hi, 
Love and appreciate the work you put into this. It's an awesome tool! 

Recently I've been trying to retrain it to be able to remove the alterations I get with a reflector telescope. I've been trying to get others interested enough to give me some sample images so that I can do a nice long training run... 

Do you have any advice on the types of image that will improve the training? I first trained it for 70 epochs with 5 whole images that I prepared, but the output images weren't getting any better at removing the diffractions spikes, which I figured was because it was seeing them too infrequently on the whole images. After that, I tried using smaller images where I had just had clipped out the stars with spikes, but the output I'm getting now is very blocky...

![image](https://user-images.githubusercontent.com/4738389/86532146-7e95d100-bebf-11ea-9edb-1ede3b8f9f53.png)

I'd appreciate any advice on the type and number I'd need for a good training set! I'm just starting again now from fresh wit the 5 original images... on Epoch 50...

**Comment by nekitmm** [comment]
This is weird result. What image size  do you use for input? 256 by 256? What learning rates do you use? I would try to increase those and train for less, you should not need 50 or 70 epochs to see improvements. 

From what I see is that you have too many examples of huge stars in your datasets and neural net starts to try and remove all the bright areas that it sees.

**Comment by nekitmm** [comment]
Remember that your training dataset should be representative of what you will be feeding in. Just cropping a bunch of huge stars and nothing else is a bad Idea.

**Comment by Leepee** [comment]
Thanks, I appreciate your time to reply! This is a good introduction to neural nets for me, I'm super new to working it out. I now realise that the learning rates are important, and are dependant on the input data. I was mainly feeding it crops of big "problem stars" and I can see that's what caused the issue. The graphs went to hell when I did that.

I was a little surprised that there aren't more people wanting to cooperate with some data with me on this, nor have I seen much about people training it on any of the forums. It's an awesome toy :)

I'm training new weights now overnight to see how it goes. I'm using a gtx1080, and I'm finding the ram throughput is my bottleneck, the gpu is nearly idle most of the time and it's 15-20 mins per epoch. The lower resolution images made this go much faster.

How many images is a reasonable training set? I'm used to seeing 10s of thousands in other studies of input samples!
